当错误发生时的处理办法:
1.停止执行代码。方法简单粗暴但是过于激烈。
2.不在类中直接处理错误，而是返回某种错误标志。
这种方法有一个问题:返回值的类型不确定。

1.抛出异常
解决办法:使用Exception类 客户端代码可以根据确定的异常类的类型来做自己的异常处理
见代码4.6.1

问题:在调用可能抛出异常的代码时，调用方(客户端代码)该如何处理抛出的异常呢？
如果调用可能会抛出异常的方法，那么应该把调用语句放在try子句中
try子句必须跟着至少一个catch子句，才能处理错误
见代码4.6.2

2.异常的子类化(创建自定义的异常类)
创建自定义的异常类的原因:
    1. 扩展异常类的功能
    2. 子类定义了新的异常类型，可以进行自己特有的错误处理。
见代码4.6.3